### ISSUE TITLE
Fix backwards compatibility for clojure.set specs

### ISSUE THREAD

**Issue by eerohele** [borkdude/speculative#161]
The specs in #152 break a significant amount of existing code. According to Alex Miller, that means the specs are wrong.

[This Gist](https://gist.github.com/eerohele/0dd0606213331c2dc5e3b8df2b21f352), extracted from the results of a [Coal Mine](https://github.com/mfikes/coal-mine) run, lists a large number of cases the specs should allow. It's obviously by no means an exhaustive list, but it's a starting point.

Users who want to avoid some of the common errors that passing non-set args to clojure.set functions can cause can use e.g. @jafingerhut's [Funjible](https://github.com/jafingerhut/funjible).

**Comment by borkdude** [comment]
First of all, not all code that happens to work should be accounted for, but only the use cases that are regarded as intended use. E.g.:

`(merge [1 2 3] 4)` is not something we want to support. `conj` is really the function users should be using for this.

However, we should account for the following use cases:

```
(set/difference set non-set)
```

and

```
(set/subset? non-set set)
```

Both usages return sets and coercion of the non-set args into sets are not needed by the user.  According to @puredanger these usages should be accounted for.

Specifically I think:

*  In `(set/difference set non-set)` the `non-set` args should be [speculative.specs/coercible-coll](https://github.com/slipset/speculative/blob/master/src/speculative/specs.cljc#L70)

* In `(set/subset? non-set set)` the `non-set` arg should be `seqable?`

The usage `(set/union non-set non-set)` should not be accounted for in my opinion: this usage does not return a set and there is no reliable way to get a set by only making the first, second, third etc. arg a set.

**Comment by jafingerhut** [comment]
+1 on the usage of `(set/union non-set non-set)` mentioned by @borkdude.  The implementation of `union` when given a mixture of sets and non-sets depends upon the `count` value of the arguments, not upon the position in which those arguments are given, so unless the caller knows about this and restricts themselves to usages with certain relative set vs. non-set counts, they will not get back what they hope.

**Comment by gnl** [comment]
Haven't had much time to think about this, so here's a couple of quick thoughts off the top of my head:

- I think that when in doubt, the specs should err on the side of strictness while allowing common, established usages as @borkdude said. `clojure.core` functions can often handle non-sensical arguments without dying and that's not a good thing. Most recent WTF example from a minute ago:
```
user=> (set/subset? [1 2 3] "asdf")
true
user=>
```
Let's not be JavaScript.

- The problem with `seqable?` as the spec for the non-set args is that it includes strings – the functions mentioned above don't work with strings.

**Comment by jafingerhut** [comment]
@borkdude Regarding allowing `(set/subset? non-set set)` uses as not violating a spec, consider this current behavior in Clojure:
```
user=> (s/subset? [1 2 3 4] #{1 2 3 4 5})
true   ;; that looks reasonable

user=> (s/subset? [1 2 3 4 1 2 3 4] #{1 2 3 4 5})
false   ;; huh?  Happens because of `count` checks in clojure.set/subset? implementation.
```

**Comment by borkdude** [comment]
Given the comments by @jafingerhut and @gnl I am no longer convinced that `set/subset?` should account for non-set inputs. Adapted my first comment to reflect that. 

`set/difference` seems to work with strings and `seqable?` doesn't pose a problem there:

```
(set/difference #{\a \b \c \d} "ab" "c") ;;=> #{\d}
```

Note that `seqable?` is also true for arrays and these also work:

```
(set/difference #{5 6 7} (into-array [5 6])) ;;=> #{7}
```

so my proposal to relax the spec for the but-first args to `reducible-coll` still stands, until proven that this may not be a good idea.

**Comment by eerohele** [comment]
>Also specs don't break code.

Yes, bad wording on my part. The way I understood Alex's comment was that if the specs indicate that code that works "as expected" is wrong, then the specs are wrong. But it's possible that I'm interpreting this too widely.

While I certainly agree that `set/union` and others can behave unexpectedly when passed non-set args, calls such as `(clojure.set/union #{1 2} [2 3])` return the "expected" result and should therefore be allowed by the specs, I guess? The problem is that it might not be very easy to discover all such cases.

>The problem with seqable? as the spec for the non-set args is that it includes strings – the functions mentioned above don't work with strings.

Well, I guess you could argue that this "works" (the [Coal Mine](https://gist.github.com/eerohele/0dd0606213331c2dc5e3b8df2b21f352) has a small number of cases like this):

```clojure
(clojure.set/subset? "A" (set "AB"))
=> true
(clojure.set/subset? "C" (set "AB"))
=> false
```

>However, a spec that is clearly lacking and does not account for usage of a function that is well established in the community and falls within the scope of intended and defined use, should be improved.

We can probably come up with a bunch of things that yield results that are so unexpected that no one would consider them defined and I think it's OK if the specs disallow those. Although we might end up needing to write quite a lot of specs to cover all the permutations.

One problem is that I don't know that there's a resource that says what is "intended and defined use" for the clojure.set functions, for example. The only somewhat authoritative comment I've found is this one by Alex Miller:

>This was done somewhat intentionally for performance reasons - rather than validate or transform, just assume they are sets - *their behavior when passed non-sets is considered undefined*.

However, these statements are at odds:

- Allow args that work as expected
- Only account for "defined" behavior

After all, in some cases, args that are considered undefined work as expected.

Anyhow, maybe I'm complicating things needlessly here. Wouldn't be the first time. Please let me know if you think that's the case. :)

**Comment by borkdude** [comment]
@eerohele I think one criterium is that our specs should work for the types of input we defined. E.g. the ret spec should be valid for that the function returns.

In the case of `set/union` with non-set args, you cannot reliably guarantee that it will return a set. It depends on the size of the input args. This is too fragile to account for in my opinion.

Same for `set/subset?` as @jafingerhut pointed out:

```
(clojure.set/subset? "AAA" (set "AB"))
```

The only function we can relax consistently is `set/difference` where only the first arg has to be a set and the rest can be reducible colls. If you agree on that one, PR welcome.

**Comment by eerohele** [comment]
That sounds like reasonable approach to me. I can make the PR when I get the time.

**Comment by borkdude** [comment]
Detected usage of `set/difference` with set + non-set seqable argument in the wild:

* solution-49c06c62 in coal-mine calls it with args `#{[:a :a]} ([:a :a])`
* I did it myself in one or two advent-of-code solutions, e.g.:
https://github.com/borkdude/advent-of-cljc/blob/4e4c3e407780fffb62d33ba995a0594352de4701/src/aoc/y2018/d07/borkdude.cljc#L96

**Comment by jafingerhut** [comment]
Note that those kinds of calls only seem to work correctly if the count of the first arg is >= the count of the second arg.  If <, set/difference calls contains? on the second arg:
```
user=> (set/difference #{[:a :a]} '([:a :a]))
#{}     ;; looks good

user=> (set/difference #{[:a :a]} '([:a :a] [:b :b]))
Execution error (IllegalArgumentException) at user/eval143 (REPL:1).
contains? not supported on type: clojure.lang.PersistentList
```

**Comment by borkdude** [comment]
@jafingerhut Very good point, I have overlooked that. 
@eerohele I think the specs are OK as they are and we shouldn't change anything right now (until, one day, maybe the set functions will coerce).
