### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by borkdude** [borkdude/speculative#262]
Idea: something with a question mark in the center and the recognizable colors from the official Clojure  logo.

**Comment by tonsky** [comment]
Well, this is what I ended up with
![frame](https://user-images.githubusercontent.com/285292/51850334-95331280-2332-11e9-945d-71dfa19af967.png)
Let me know what you think! If you like it, I’ll upload vector sources and different resolutions somewhere

**Comment by borkdude** [comment]
@tonsky Good job! No `::` or question mark though? Upload sounds good :-).

**Comment by tonsky** [comment]
Couldn’t make anything of them, although as ideas they are good

**Comment by borkdude** [comment]
@tonsky A'ight, let's go for this one then 👍
